from _typeshed import Incomplete
from typing import Any

from django.http import HttpRequest

DEFAULT_SETTING_VALUES: dict[str, Any]

def choose_username(email: str) -> str: ...
def decode_pk(encoded_pk: str) -> str: ...
def encode_pk(pk: str) -> str: ...
def flush_old_tmp_users(days: int = 1) -> int: ...
def get_account_username_split(username: str) -> tuple[str, str, str]: ...
def get_input(prompt: str) -> str: ...
def get_protocol(request: HttpRequest) -> str: ...
def get_random_username() -> str: ...

def get_redirect_url(
        request: HttpRequest,
        use_referer: bool = False,
        default_url: Incomplete | None = None,
) -> str: ...

def get_service_url(
        request: HttpRequest,
        redirect_url: Incomplete | None = None,
) -> str: ...

def get_setting(setting_name: str) -> Any: ...
def is_tmp_user(user: Incomplete) -> bool: ...
def is_unlinked_account(user: Incomplete) -> bool: ...
